### ISSUE TITLE
SyntaxError in line 35 of data_processing.smk: invalid syntax

### ISSUE THREAD

**Issue by shenscore** [LuJiansen/scNanoHi-C#3]
`snakemake -s data_processing.smk`

```
SyntaxError in line 35 of /mnt/e/scNanohic/preprocess/data_processing.smk:
invalid syntax
```

how to fix this?

**Comment by shenscore** [comment]
fixed after update snakemake.

**Comment by PhoenixMWJ** [comment]
Hi, I have a question. Where did you get the input file bc_index? Thank you.

**Comment by PhoenixMWJ** [comment]
Hi, I have a question. Where did you get the input file bc_index? Thank you.

**Comment by PhoenixMWJ** [comment]
> > Hi, I have a question. Where did you get the input file bc_index? Thank you.
> 
> The details about bc_index have been described in the README, which contains the Tn5 and PCR barcodes used in the sequencing library.

This file needs to be generated according to GSE217189_scNanoHi-C_barcode_information.xlsx, right?

**Comment by PhoenixMWJ** [comment]
> > > > Hi, I have a question. Where did you get the input file bc_index? Thank you.
> > > 
> > > 
> > > The details about bc_index have been described in the README, which contains the Tn5 and PCR barcodes used in the sequencing library.
> > 
> > 
> > This file needs to be generated according to GSE217189_scNanoHi-C_barcode_information.xlsx, right?
> 
> yes, that's how I generate the bc_index file

How does an optional library name correspond to A, B, and C?

**Comment by shenscore** [comment]
> > > > > Hi, I have a question. Where did you get the input file bc_index? Thank you.
> > > > 
> > > > 
> > > > The details about bc_index have been described in the README, which contains the Tn5 and PCR barcodes used in the sequencing library.
> > > 
> > > 
> > > This file needs to be generated according to GSE217189_scNanoHi-C_barcode_information.xlsx, right?
> > 
> > 
> > yes, that's how I generate the bc_index file
> 
> How does an optional library name correspond to A, B, and C?

the first column: PCR barcodes ID
the second and third: start and end of Tn5 barcode
the fourth: your library name

**Comment by PhoenixMWJ** [comment]
> > > > > > Hi, I have a question. Where did you get the input file bc_index? Thank you.
> > > > > 
> > > > > 
> > > > > The details about bc_index have been described in the README, which contains the Tn5 and PCR barcodes used in the sequencing library.
> > > > 
> > > > 
> > > > This file needs to be generated according to GSE217189_scNanoHi-C_barcode_information.xlsx, right?
> > > 
> > > 
> > > yes, that's how I generate the bc_index file
> > 
> > 
> > How does an optional library name correspond to A, B, and C?
> 
> the first column: PCR barcodes ID the second and third: start and end of Tn5 barcode the fourth: your library name

In README, the fourth column of bc_index is A, B, C. How does it correspond to the fourth column in GSE217189_scNanoHi-C_barcode_information.xlsx?

**Comment by LuJiansen** [comment]
> > > > > > > Hi, I have a question. Where did you get the input file bc_index? Thank you.
> > > > > > 
> > > > > > 
> > > > > > The details about bc_index have been described in the README, which contains the Tn5 and PCR barcodes used in the sequencing library.
> > > > > 
> > > > > 
> > > > > This file needs to be generated according to GSE217189_scNanoHi-C_barcode_information.xlsx, right?
> > > > 
> > > > 
> > > > yes, that's how I generate the bc_index file
> > > 
> > > 
> > > How does an optional library name correspond to A, B, and C?
> > 
> > 
> > the first column: PCR barcodes ID the second and third: start and end of Tn5 barcode the fourth: your library name
> 
> In README, the fourth column of bc_index is A, B, C. How does it correspond to the fourth column in GSE217189_scNanoHi-C_barcode_information.xlsx?

This column is optional, I often leave it empty because usually we only have one library in a Nanopore run.
